/**
 * champion-build-stats — the closed set of valid `Champion_Key`s and their
 * display names (specs/champion-build-stats/ task 1.2).
 *
 * GENERATED FILE. Do not hand-edit the map below. Regenerate it with:
 *
 *     node backend/scripts/generateChampionKeys.mjs
 *
 * which fetches Data Dragon `champion.json` at the version pinned in
 * `backend/.env.example` (`DDRAGON_VERSION`) and rewrites the list.
 *
 * Why a bundled list rather than a runtime fetch: the endpoint needs to tell "is
 * this a champion key" from "is this junk" so it can 404 (Requirement 10.3), and
 * needs the display name for the response's `champion.name` (Requirement 11.1).
 * The set changes a few times a year, on a Riot patch we already redeploy for
 * (the frontend's `DDRAGON_VERSION` bump). A runtime Data Dragon fetch + cache
 * would be the backend's first, for data this small and slow-moving.
 */

export const CHAMPION_KEYS_DDRAGON_VERSION = '16.17.1';

/** `Champion_Key` → display name, at `CHAMPION_KEYS_DDRAGON_VERSION`, sorted by key. */
export const CHAMPION_NAMES: ReadonlyMap<string, string> = new Map<string, string>([
  ['Aatrox', "Aatrox"],
  ['Ahri', "Ahri"],
  ['Akali', "Akali"],
  ['Akshan', "Akshan"],
  ['Alistar', "Alistar"],
  ['Ambessa', "Ambessa"],
  ['Amumu', "Amumu"],
  ['Anivia', "Anivia"],
  ['Annie', "Annie"],
  ['Aphelios', "Aphelios"],
  ['Ashe', "Ashe"],
  ['AurelionSol', "Aurelion Sol"],
  ['Aurora', "Aurora"],
  ['Azir', "Azir"],
  ['Bard', "Bard"],
  ['Belveth', "Bel'Veth"],
  ['Blitzcrank', "Blitzcrank"],
  ['Brand', "Brand"],
  ['Braum', "Braum"],
  ['Briar', "Briar"],
  ['Caitlyn', "Caitlyn"],
  ['Camille', "Camille"],
  ['Cassiopeia', "Cassiopeia"],
  ['Chogath', "Cho'Gath"],
  ['Corki', "Corki"],
  ['Darius', "Darius"],
  ['Diana', "Diana"],
  ['Draven', "Draven"],
  ['DrMundo', "Dr. Mundo"],
  ['Ekko', "Ekko"],
  ['Elise', "Elise"],
  ['Evelynn', "Evelynn"],
  ['Ezreal', "Ezreal"],
  ['Fiddlesticks', "Fiddlesticks"],
  ['Fiora', "Fiora"],
  ['Fizz', "Fizz"],
  ['Galio', "Galio"],
  ['Gangplank', "Gangplank"],
  ['Garen', "Garen"],
  ['Gnar', "Gnar"],
  ['Gragas', "Gragas"],
  ['Graves', "Graves"],
  ['Gwen', "Gwen"],
  ['Hecarim', "Hecarim"],
  ['Heimerdinger', "Heimerdinger"],
  ['Hwei', "Hwei"],
  ['Illaoi', "Illaoi"],
  ['Irelia', "Irelia"],
  ['Ivern', "Ivern"],
  ['Janna', "Janna"],
  ['JarvanIV', "Jarvan IV"],
  ['Jax', "Jax"],
  ['Jayce', "Jayce"],
  ['Jhin', "Jhin"],
  ['Jinx', "Jinx"],
  ['Kaisa', "Kai'Sa"],
  ['Kalista', "Kalista"],
  ['Karma', "Karma"],
  ['Karthus', "Karthus"],
  ['Kassadin', "Kassadin"],
  ['Katarina', "Katarina"],
  ['Kayle', "Kayle"],
  ['Kayn', "Kayn"],
  ['Kennen', "Kennen"],
  ['Khazix', "Kha'Zix"],
  ['Kindred', "Kindred"],
  ['Kled', "Kled"],
  ['KogMaw', "Kog'Maw"],
  ['KSante', "K'Sante"],
  ['Leblanc', "LeBlanc"],
  ['LeeSin', "Lee Sin"],
  ['Leona', "Leona"],
  ['Lillia', "Lillia"],
  ['Lissandra', "Lissandra"],
  ['Locke', "Locke"],
  ['Lucian', "Lucian"],
  ['Lulu', "Lulu"],
  ['Lux', "Lux"],
  ['Malphite', "Malphite"],
  ['Malzahar', "Malzahar"],
  ['Maokai', "Maokai"],
  ['MasterYi', "Master Yi"],
  ['Mel', "Mel"],
  ['Milio', "Milio"],
  ['MissFortune', "Miss Fortune"],
  ['MonkeyKing', "Wukong"],
  ['Mordekaiser', "Mordekaiser"],
  ['Morgana', "Morgana"],
  ['Naafiri', "Naafiri"],
  ['Nami', "Nami"],
  ['Nasus', "Nasus"],
  ['Nautilus', "Nautilus"],
  ['Neeko', "Neeko"],
  ['Nidalee', "Nidalee"],
  ['Nilah', "Nilah"],
  ['Nocturne', "Nocturne"],
  ['Nunu', "Nunu & Willump"],
  ['Olaf', "Olaf"],
  ['Orianna', "Orianna"],
  ['Ornn', "Ornn"],
  ['Pantheon', "Pantheon"],
  ['Poppy', "Poppy"],
  ['Pyke', "Pyke"],
  ['Qiyana', "Qiyana"],
  ['Quinn', "Quinn"],
  ['Rakan', "Rakan"],
  ['Rammus', "Rammus"],
  ['RekSai', "Rek'Sai"],
  ['Rell', "Rell"],
  ['Renata', "Renata Glasc"],
  ['Renekton', "Renekton"],
  ['Rengar', "Rengar"],
  ['Riven', "Riven"],
  ['Rumble', "Rumble"],
  ['Ryze', "Ryze"],
  ['Samira', "Samira"],
  ['Sejuani', "Sejuani"],
  ['Senna', "Senna"],
  ['Seraphine', "Seraphine"],
  ['Sett', "Sett"],
  ['Shaco', "Shaco"],
  ['Shen', "Shen"],
  ['Shyvana', "Shyvana"],
  ['Singed', "Singed"],
  ['Sion', "Sion"],
  ['Sivir', "Sivir"],
  ['Skarner', "Skarner"],
  ['Smolder', "Smolder"],
  ['Sona', "Sona"],
  ['Soraka', "Soraka"],
  ['Swain', "Swain"],
  ['Sylas', "Sylas"],
  ['Syndra', "Syndra"],
  ['TahmKench', "Tahm Kench"],
  ['Taliyah', "Taliyah"],
  ['Talon', "Talon"],
  ['Taric', "Taric"],
  ['Teemo', "Teemo"],
  ['Thresh', "Thresh"],
  ['Tristana', "Tristana"],
  ['Trundle', "Trundle"],
  ['Tryndamere', "Tryndamere"],
  ['TwistedFate', "Twisted Fate"],
  ['Twitch', "Twitch"],
  ['Udyr', "Udyr"],
  ['Urgot', "Urgot"],
  ['Varus', "Varus"],
  ['Vayne', "Vayne"],
  ['Veigar', "Veigar"],
  ['Velkoz', "Vel'Koz"],
  ['Vex', "Vex"],
  ['Vi', "Vi"],
  ['Viego', "Viego"],
  ['Viktor', "Viktor"],
  ['Vladimir', "Vladimir"],
  ['Volibear', "Volibear"],
  ['Warwick', "Warwick"],
  ['Xayah', "Xayah"],
  ['Xerath', "Xerath"],
  ['XinZhao', "Xin Zhao"],
  ['Yasuo', "Yasuo"],
  ['Yone', "Yone"],
  ['Yorick', "Yorick"],
  ['Yunara', "Yunara"],
  ['Yuumi', "Yuumi"],
  ['Zaahen', "Zaahen"],
  ['Zac', "Zac"],
  ['Zed', "Zed"],
  ['Zeri', "Zeri"],
  ['Ziggs', "Ziggs"],
  ['Zilean', "Zilean"],
  ['Zoe', "Zoe"],
  ['Zyra', "Zyra"],
]);

/** Every valid `Champion_Key`. */
export const CHAMPION_KEYS: ReadonlySet<string> = new Set<string>(CHAMPION_NAMES.keys());

/**
 * Requirement 10.3: whether `:championKey` names a real champion. The endpoint
 * 404s when this is `false` and never touches the stats store.
 */
export function isKnownChampionKey(key: string): boolean {
  return CHAMPION_KEYS.has(key);
}

/** The display name for a `Champion_Key` (Requirement 11.1); the key itself if unknown. */
export function championDisplayName(key: string): string {
  return CHAMPION_NAMES.get(key) ?? key;
}
